name: Unzip Bot
on: workflow_dispatch
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip and move files
        run: |
          unzip -o BODY-Bot-main.zip
          rm BODY-Bot-main.zip
          shopt -s dotglob
          mv -v BODY-Bot-main/* . 2>/dev/null || true
          rmdir BODY-Bot-main || true
          rm -rf .github/workflows/unzip.yml
          rm -rf BODY-Bot-main.zip
      - uses: stefanzweifel/git-auto-commit-action@v5
